# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: TotalDwarf.dev
description: A Summary Page for Kieran Pritchard.
baseurl: ""
url: https://totaldwarf.dev

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Kieran Pritchard
  description:
    - Hi!
    - Welcome to TotalDwarf.dev.
    - A website to show you everything about me!
    - Please have a look around!
  cv: assets/cv.pdf
  navigation:
    Experience: experience
    Education: education
    Projects: projects
  contact:
    phone: 07951 357755
    email: kierock03@gmail.com
  profiles:
    Github: https://github.com/TotalDwarf03
    Linkedin: https://www.linkedin.com/in/kieran-pritchard-20a270193/
  Repo: https://github.com/TotalDwarf03/TotalDwarf03.github.io

experience:
  title: Experience
  description:
    - Here is a list of my recent experiences
    - For more information please check out my Linkedin!

education:
  title: Education
  description:
    - Here are some details about my education
    - For more information please check out my Linkedin!

projects:
  title: Projects
  description:
    - Here are some of my favourite projects
    - To see more of my projects, visit my Github!

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
