site_name: TotalDwarf.dev
site_url: "https://totaldwarf.dev/"

site_description: "A personal portfolio about Kieran Pritchard (TotalDwarf03)"
site_author: "Kieran Pritchard"

repo_url: https://github.com/TotalDwarf03/TotalDwarf03.github.io
repo_name: TotalDwarf03.github.io

nav:
  - Home: 'index.md'
theme:
  name: material
  language: en

  palette:
    # toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  font:
    text: ubuntu
    code: ubuntu mono

  favicon: ./assets/favicon.ico

  icon:
    logo: fontawesome/solid/computer
    repo: fontawesome/brands/github

  features:
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer

    - toc.integrate

    - search.suggest

    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TotalDwarf03

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kieran-pritchard-20a270193/

    - icon: fontawesome/solid/paper-plane
      link: mailto:kieran@totaldwarf.dev

plugins:
  - git-revision-date-localized:
      type: date
  - search

copyright: Copyright &copy; 2024 Kieran Pritchard